package gameOfLife;

import gameOfLife.simulator.Simulator;
import gameOfLife.gui.BoardDisplay;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.text.Font;
import javafx.stage.Stage;

public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception{
        //Create simulator with the probability for a cell to be alive at game start and initiate the game
        Simulator simulator = new Simulator(0.9);
        simulator.initiateGame();

        //set up the primary stage and create a scene with the root generated by the BoardDisplay
        Font.loadFont(getClass().getResource("/fonts/VarelaRound-Regular.ttf").toExternalForm(), 10);
        primaryStage.setTitle("The Game of Life");
        primaryStage.setScene(new Scene(BoardDisplay.getRoot()));
        primaryStage.getScene().getStylesheets().add("/styles.css");
        primaryStage.setResizable(false);
        primaryStage.sizeToScene();
        primaryStage.show();
    }


    public static void main(String[] args) {
        launch(args);
    }
}
